/**
 * Icon barrel — all icons used in this library come from here.
 * Source: lucide-react (https://lucide.dev)
 *
 * Import pattern:
 *   import { Plus, ChevronDown, Search } from '../lib/icons'
 *
 * If you ever swap the icon library, change only this file.
 * Every icon is a React component that accepts: size, color, strokeWidth, className
 *
 * Default overrides applied via re-export wrapper:
 *   - strokeWidth: 1.7  (matches our thin UI aesthetic — Vercel/Linear style)
 *   - size: 16          (default inline size; override per-use)
 */

export {
  // ── Navigation & UI chrome ──────────────────────────────────────────────────
  ScanLine,
  ScanSearch,
  ScanBarcode,
  ArrowUpRight,
  ArrowDownRight,
  ArrowUpLeft,
  ArrowDownLeft,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Menu,
  X,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  MoveRight,
  ExternalLink,
  Link,
  Home,
  Search,
  Filter,
  SlidersHorizontal,
  MoreHorizontal,
  MoreVertical,
  PanelLeft,
  PanelRight,

  // ── Actions ─────────────────────────────────────────────────────────────────
  Plus,
  Minus,
  Pencil,
  Pen,
  Edit,
  Edit2,
  Edit3,
  Trash,
  Trash2,
  Copy,
  Clipboard,
  ClipboardCheck,
  Download,
  Upload,
  Share,
  Share2,
  Send,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Undo,
  Redo,
  Save,
  Bookmark,
  BookmarkCheck,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Flag,
  Pin,
  Lock,
  Unlock,
  LogIn,
  LogOut,
  Eye,
  EyeOff,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  ZoomIn,
  ZoomOut,
  Crop,

  // ── Status & Feedback ────────────────────────────────────────────────────────
  Check,
  CheckCircle,
  CheckCircle2,
  XCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Loader,
  Loader2,
  Circle,
  Dot,

  // ── Content & Media ──────────────────────────────────────────────────────────
  Image,
  Images,
  FileImage,
  Video,
  Film,
  Music,
  Mic,
  MicOff,
  Volume,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Repeat,
  Shuffle,

  // ── Files & Folders ──────────────────────────────────────────────────────────
  File,
  FileText,
  FileCode,
  FilePlus,
  FileMinus,
  Folder,
  FolderOpen,
  FolderPlus,
  Archive,

  // ── Layout & Design ──────────────────────────────────────────────────────────
  Layout,
  LayoutGrid,
  LayoutList,
  Grid,
  Grid2X2,
  Grid3X3,
  List,
  Table,
  Table2,
  Columns,
  Rows,
  Layers,
  Component,
  Frame,
  Sliders,
  Move,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,

  // ── Communication ────────────────────────────────────────────────────────────
  Mail,
  MailOpen,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Bell,
  BellOff,
  BellRing,
  Phone,
  PhoneCall,
  PhoneOff,
  Smartphone,
  Tablet,
  Monitor,
  Laptop,
  AtSign,
  Inbox,

  // ── People & Identity ────────────────────────────────────────────────────────
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Users,
  CircleUser,
  Contact,

  // ── Data & Analytics ─────────────────────────────────────────────────────────
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  LineChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Gauge,
  Database,
  Server,
  Cpu,
  HardDrive,
  Cloud,
  CloudUpload,
  CloudDownload,

  // ── Development & Code ───────────────────────────────────────────────────────
  Code,
  Code2,
  CodeXml,
  Terminal,
  Bug,
  Braces,
  GitBranch,
  GitFork,
  GitCommitHorizontal,
  GitMerge,
  GitPullRequest,
  Package,
  Github,

  // ── Social & Brand ───────────────────────────────────────────────────────────
  Twitter,
  Linkedin,
  Chrome,

  // ── Settings & Config ────────────────────────────────────────────────────────
  Settings,
  Settings2,
  Cog,
  Wrench,
  SlidersVertical,
  ToggleLeft,
  ToggleRight,
  Palette,
  Paintbrush,
  Wand2,
  Sparkles,

  // ── Commerce ─────────────────────────────────────────────────────────────────
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  DollarSign,
  Percent,
  Tag,
  Tags,
  Receipt,
  Wallet,
  Coins,

  // ── Time & Date ──────────────────────────────────────────────────────────────
  Clock,
  Clock3,
  Clock8,
  Timer,
  Calendar,
  CalendarCheck,
  CalendarPlus,

  // ── Maps & Location ──────────────────────────────────────────────────────────
  Map,
  MapPin,
  Navigation,
  Globe,
  Globe2,
  Compass,

  // ── Misc ─────────────────────────────────────────────────────────────────────
  Moon,
  Sun,
  SunMoon,
  Zap,
  ZapOff,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Key,
  Fingerprint,
  Smile,
  Frown,
  Meh,
  Award,
  Trophy,
  Lightbulb,
  Rocket,
  Newspaper,
  BookOpen,
  GraduationCap,
  Leaf,
  Flower,
  Apple,
} from 'lucide-react'
